POST http://localhost:5184/sales
content-type: application/json

{
  "customer_id": 1,
  "payment_method": "Store credit",
  "items": [
    {
      "product_id": 1,
      "quantity": 0
    }
  ]
}


####################

GET http://localhost:5184/sales
